config/routes.rb
# == Route Map
#
#                          Prefix Verb   URI Pattern                                                                                       Controller#Action
#  delete_picture_attachment_user DELETE /users/:id/delete_picture_attachment(.:format)                                                    users#delete_picture_attachment
#                           users GET    /users(.:format)                                                                                  users#index
#                                 POST   /users(.:format)                                                                                  users#create
#                        new_user GET    /users/new(.:format)                                                                              users#new
#                       edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
#                            user PATCH  /users/:id(.:format)                                                                              users#update
#                                 PUT    /users/:id(.:format)                                                                              users#update
#                                 DELETE /users/:id(.:format)                                                                              users#destroy
#              rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
#        rails_service_blob_proxy GET    /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
#                                 GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
#       rails_blob_representation GET    /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
# rails_blob_representation_proxy GET    /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
#                                 GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
#              rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
#       update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
#            rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :users, except: %i[show] do
    member do
      delete :delete_picture_attachment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  email      :string           not null
#  gender     :integer
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  validates :name, :email, presence: true, allow_blank: false

  has_one_attached :picture

  enum gender: {
    male: 0,
    female: 1
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :load_user, only: %i[edit]

  def index
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(params) }
    end
  end

  def new
    @user = User.new
  end

  def create
    service = UserService.new(create_params)

    service.create

    if service.success?
      flash[:success] = 'Usuário criado com sucesso!'
    else
      flash[:error] = service.errors.join(', ')
    end

    redirect_to action: :new
  end

  def edit; end

  def update
    service = UserService.new(update_params)

    service.update(record_id)

    if service.success?
      flash[:success] = 'Usuário alterado com sucesso!'
    else
      flash[:error] = service.errors.join(', ')
    end
    redirect_to action: :edit
  end

  def destroy
    service = UserService.new

    service.destroy(record_id)

    flash[:error] = service.errors.join(', ') unless service.success?

    redirect_to action: :index
  end

  def delete_picture_attachment
    picture = ActiveStorage::Attachment.find(params[:id])
    picture.purge

    redirect_back(fallback_location: { action: 'edit', id: picture.record.id })
  rescue StandardError => e
    flash[:error] = e.message
    redirect_back(fallback_location: { action: 'edit' })
  end

  protected

  def create_params
    params.require(:user).permit(:name, :email, :gender, :picture)
  end

  def update_params
    create_params
  end

  def record_id
    params[:id]
  end

  def load_user
    @user = User.find(record_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImportUsers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.8/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.8/css/jquery.dataTables.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type.to_s %>">
            <%= message %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-3 mt-5 text-center">
        <% if @user&.id.present? && @user&.picture.present? %>
          <%= image_tag @user.picture, style: "width: 200px; margin-right: 5px;" %>
          <div class="d-grid gap-2 mx-2 my-2">
            <%= link_to 'Remover', delete_picture_attachment_user_path(@user.picture.id), class: "btn btn-danger",
                method: :delete,
                data: { confirm: 'Tem certeza que deseja remover a imagem?' } %>
          </div>
        <% end %>
      </div>

      <div class="col-md-6">
        <div class="mb-3">
          <label for="name" class="form-label">Nome</label>
          <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <label for="email" class="form-label">Email</label>
          <%= form.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <label for="gender" class="form-label">Gênero</label>
          <%= form.select :gender, [['Masculino', 'male'], ['Feminino', 'female']], { prompt:'' }, { class: "form-control" } %>
        </div>
        <div class="mb-3">
          <label for="picture" class="form-label">Foto</label>
          <%= form.file_field :picture, multiple: false, accept:'image/*', class: "form-control" %>
        </div>
      </div>

      <div class="col-md-6 offset-md-3">
        <div class="mt-3">
          <button type="submit" class="btn btn-primary">Salvar</button>
          <% if @user&.id.present? %>
            <%= link_to 'Excluir', user_path(@user.id), class: "btn btn-danger",
                  method: :delete,
                  data: { confirm: 'Tem certeza que deseja excluir esse usuário?' } %>
          <% end %>
          <%= link_to "Voltar", users_path, class: "btn btn-dark" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container mt-5">
  <h3>Edição de Usuário</h3>

  <input name="_method" type="hidden" value="patch" />
  <%= render partial: "form" %>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
  <h3 style="margin: 0;display: inline-block;">Listagem de Usuários</h3>
  <a href="/" class="btn btn-dark mx-3" style="float: right;">Voltar</a>
  <%= link_to "Novo Usuário", new_user_path, class: "btn btn-primary", style: "float: right;" %>

  <div class="row mt-5">
    <table id="users-datatable" data-source="<%= users_path(format: :json) %>">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>

<script>
  $(document).ready(function() {
    const that = this;

    this.datatable = $('#users-datatable').DataTable( {
      processing: true,
      serverSide: true,
      lengthMenu: [[10, 15], [10, 15]],
      language: { url: `//cdn.datatables.net/plug-ins/1.11.3/i18n/pt_br.json` },
      ajax: {
        url: $('#users-datatable').data('source')
      },
      pagingType: 'full_numbers',
      columns: [
        { data: 'name' },
        { data: 'email' },
        { data: 'id', title: '', class: 'text-center', render: (data, type, row) => {
          return `
            <a title="Editar" target="_blank" class="btn btn-warning edit-button">
              Editar
            </a> \
            <a title="Excluir" target="_blank" class="btn btn-danger delete-button">
              Excluir
            </a>`;
        } }
      ]
    } );

    $('#users-datatable tbody').on('click', '.edit-button', function(event) {
      const data = that.datatable.row($(this).parents('tr')).data();

      window.location = `${window.location.href}/${data.id}/edit`;
    });

    $('#users-datatable tbody').on('click', '.delete-button', function(event) {
      const data = that.datatable.row($(this).parents('tr')).data();

      if (window.confirm('Tem certeza que deseja excluir esse usuário?')) {
        fetch('http://localhost:3000/users/' + data.id, {
          method: 'DELETE',
        })
        .then(() => {
          alert('Usuário excluído com sucesso!');
          $('#users-datatable').DataTable().ajax.reload();
        }).catch(err => {
          console.error(err);
          alert('Erro ao excluir usuário...');
        });
      }
    });
  } );
</script>

app/views/users/new.html.erb
<div class="container mt-5">
  <h3>Cadastro de Usuário</h3>

  <%= render partial: "form" %>
</div>